import 'echarts/map/js/province/anhui'; // 安徽
import 'echarts/map/js/province/aomen'; // 澳门
import 'echarts/map/js/province/beijing'; // 北京
import 'echarts/map/js/province/chongqing'; // 重庆
import 'echarts/map/js/province/fujian'; // 福建
import 'echarts/map/js/province/gansu'; // 甘肃
import 'echarts/map/js/province/guangdong'; // 广东
import 'echarts/map/js/province/guangxi'; // 广西
import 'echarts/map/js/province/guizhou'; // 贵州
import 'echarts/map/js/province/hainan'; // 海南
import 'echarts/map/js/province/hebei'; // 河北
import 'echarts/map/js/province/heilongjiang'; // 黑龙江
import 'echarts/map/js/province/henan'; // 河南
import 'echarts/map/js/province/hubei'; // 湖北
import 'echarts/map/js/province/hunan'; // 湖南
import 'echarts/map/js/province/jiangsu'; // 江苏
import 'echarts/map/js/province/jiangxi'; // 江西
import 'echarts/map/js/province/jilin'; // 吉林
import 'echarts/map/js/province/liaoning'; // 辽宁
import 'echarts/map/js/province/neimenggu'; // 内蒙古
import 'echarts/map/js/province/ningxia'; // 宁夏
import 'echarts/map/js/province/qinghai'; // 青海
import 'echarts/map/js/province/shandong'; // 山东
import 'echarts/map/js/province/shanghai'; // 上海
import 'echarts/map/js/province/shanxi'; // 山西
import 'echarts/map/js/province/shanxi1'; // 陕西
import 'echarts/map/js/province/sichuan'; // 四川
import 'echarts/map/js/province/taiwan'; // 台湾
import 'echarts/map/js/province/tianjin'; // 天津
import 'echarts/map/js/province/xianggang'; // 香港
import 'echarts/map/js/province/xinjiang'; // 新疆
import 'echarts/map/js/province/xizang'; // 西藏
import 'echarts/map/js/province/yunnan'; // 云南
import 'echarts/map/js/province/zhejiang'; // 浙江
